// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/bomba-gasolina-lima": {
    params: {};
  };
  "/comparativas": {
    params: {};
  };
  "/comparativas/:slug": {
    params: {
      "slug": string;
    };
  };
  "/local": {
    params: {};
  };
  "/local/:slug": {
    params: {
      "slug": string;
    };
  };
  "/precios": {
    params: {};
  };
  "/precios/:slug": {
    params: {
      "slug": string;
    };
  };
  "/problemas": {
    params: {};
  };
  "/problemas/:problema": {
    params: {
      "problema": string;
    };
  };
  "/servicios": {
    params: {};
  };
  "/servicios/:servicio": {
    params: {
      "servicio": string;
    };
  };
  "/zonas/:zona": {
    params: {
      "zona": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blog" | "/blog/:slug" | "/bomba-gasolina-lima" | "/comparativas" | "/comparativas/:slug" | "/local" | "/local/:slug" | "/precios" | "/precios/:slug" | "/problemas" | "/problemas/:problema" | "/servicios" | "/servicios/:servicio" | "/zonas/:zona" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./blog/page.jsx": {
    id: "blog/page";
    page: "/blog";
  };
  "./blog/[slug]/page.jsx": {
    id: "blog/[slug]/page";
    page: "/blog/:slug";
  };
  "./bomba-gasolina-lima/page.jsx": {
    id: "bomba-gasolina-lima/page";
    page: "/bomba-gasolina-lima";
  };
  "./comparativas/page.jsx": {
    id: "comparativas/page";
    page: "/comparativas";
  };
  "./comparativas/[slug]/page.jsx": {
    id: "comparativas/[slug]/page";
    page: "/comparativas/:slug";
  };
  "./local/page.jsx": {
    id: "local/page";
    page: "/local";
  };
  "./local/[slug]/page.jsx": {
    id: "local/[slug]/page";
    page: "/local/:slug";
  };
  "./precios/page.jsx": {
    id: "precios/page";
    page: "/precios";
  };
  "./precios/[slug]/page.jsx": {
    id: "precios/[slug]/page";
    page: "/precios/:slug";
  };
  "./problemas/page.jsx": {
    id: "problemas/page";
    page: "/problemas";
  };
  "./problemas/[problema]/page.jsx": {
    id: "problemas/[problema]/page";
    page: "/problemas/:problema";
  };
  "./servicios/page.jsx": {
    id: "servicios/page";
    page: "/servicios";
  };
  "./servicios/[servicio]/page.jsx": {
    id: "servicios/[servicio]/page";
    page: "/servicios/:servicio";
  };
  "./zonas/[zona]/page.jsx": {
    id: "zonas/[zona]/page";
    page: "/zonas/:zona";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "blog/page": typeof import("./src/app/./blog/page.jsx");
  "blog/[slug]/page": typeof import("./src/app/./blog/[slug]/page.jsx");
  "bomba-gasolina-lima/page": typeof import("./src/app/./bomba-gasolina-lima/page.jsx");
  "comparativas/page": typeof import("./src/app/./comparativas/page.jsx");
  "comparativas/[slug]/page": typeof import("./src/app/./comparativas/[slug]/page.jsx");
  "local/page": typeof import("./src/app/./local/page.jsx");
  "local/[slug]/page": typeof import("./src/app/./local/[slug]/page.jsx");
  "precios/page": typeof import("./src/app/./precios/page.jsx");
  "precios/[slug]/page": typeof import("./src/app/./precios/[slug]/page.jsx");
  "problemas/page": typeof import("./src/app/./problemas/page.jsx");
  "problemas/[problema]/page": typeof import("./src/app/./problemas/[problema]/page.jsx");
  "servicios/page": typeof import("./src/app/./servicios/page.jsx");
  "servicios/[servicio]/page": typeof import("./src/app/./servicios/[servicio]/page.jsx");
  "zonas/[zona]/page": typeof import("./src/app/./zonas/[zona]/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};